# Manual #
import = [ "~/.config/alacritty/themes/hyper.toml" ]

[env]
  TERM = "xterm-256color"

[window]
  opacity = 0.95

[window.padding]
    x = 15
    y = 15

[cursor]
	blink_interval = 450

[cursor.style]
	shape = "Underline"
	blinking = "on"


[font]
	size = 10

[font.normal]
  family = "SF Mono"


