# Manual #
#import = [ "~/.config/alacritty/themes/hyper.toml" ]
import = [ "~/.config/alacritty/themes/smoooooth.toml" ]

[env]
  TERM = "xterm-256color"

[window]
  opacity = 0.8

[window.padding]
    x = 15
    y = 15

[cursor]
	blink_interval = 450

[cursor.style]
	shape = "Block"
	blinking = "on"


[font]
	size = 10

[font.normal]
	family = "Fira Code"
#	family = "MesloLGS NF"
#	family = "Source Code"
#	family = "Monocraft"


