#!/bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

# Set up monitors

SCREENS_FOR_EACH_MONITOR=5

#if type "xrandr"; then
#	INITIAL=1
#	for m in $(xrandr --query | grep " connected" | cut -d" " -f1); do
#		MON=$m
#		bspc monitor $m -d 1 2 3 4 5
#	done
#fi


bspc monitor -d I II III IV V VI


# Border, gap and padding.
bspc config border_width        1 
bspc config window_gap          12
bspc config top_padding 0
bspc config bottom_padding 0

# Mouse config

# mouse follows monitor focus
bspc config pointer_follows_monitor true

# Split config

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# From TWM-G
#bspc config automatic_scheme spiral
bspc config initial_polarity first_child
bspc config removal_adjustment true
bspc config split_ratio 0.5

# Border colors from TWM-G
bspc config normal_border_color "#000000"
bspc config focused_border_color "#ffffff"
bspc config focus_follows_pointer true



# Rules
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off


# Autostart.sh script
$HOME/.startup.sh
